import { Metadata } from "next";
import localFont from "next/font/local";
import { i18n, type Locale } from "../../i18n-config";
import "./globals.css";
import Providers from "./providers";


const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function Root(props: {
    children: React.ReactNode;
    params: Promise<{ lang: Locale }>;
}) {
    const params = await props.params;

    const { children } = props;

    return (
        <html lang={params.lang}>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}